### ISSUE TITLE
[needs-docs] Refactor the New Shapefile dialog to mimic the GeoPackage sequence (#5803)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2252]
Original commit: https://github.com/qgis/QGIS/commit/571bf54d2a21458cc79592ef7f92a6157b864424 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by anitagraser** [comment]
I've fixed some issues related to creating new Shapefiles in https://github.com/qgis/QGIS-Documentation/pull/2258/files but don't have an Ubuntu machine with nightly to create screenshots.

**Comment by DelazJ** [comment]
Do not stress for that. We still have some[ pending changes](https://github.com/qgis/QGIS/pull/5830) for the dialog, so this should be done later
