### ISSUE TITLE
Rename "meters (at map scale)" unit label to "meters at scale"

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Documentation#2314]
see https://github.com/qgis/QGIS/pull/6034

**Comment by jonnyforestGIS** [comment]
Hi, i can't find this term in the documentation files? This is fixed?

**Comment by DelazJ** [comment]
No, it's not fixed. This term is never used in the documentation because the widget that shows it has never been described.
I shouldn't have tagged this as easy (meaning quick fix for beginners) because fixing it requires to describe the unit selector widget (and the sub-dialog when this option is selected). 
But if you want to give it a try, imo this description can be placed somewhere in [the general Tools chapter](https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html). My idea is at some point to move under a `common widgets` section the widgets commonly found in QGIS: color selector, unit selector, blending mode, data defined.... (most of them are already written in this chapter)

**Comment by havatv** [comment]
I suggest we close this, @DelazJ.
