### ISSUE TITLE
Processing providers and algorithm - standard hint for programmers

### ISSUE THREAD

**Issue by havatv** [qgis/QGIS-Documentation#3283]
## Description
In the "Processing providers and algorithms" section of the user guide (https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/index.html), algorithms and their parameters are described.  The parameters are listed with their user interface names.  For a developer / script creator that wants to use an algorithm, it is more useful to know the "real" names of the parameters (that have to be used when running the algorithm from Python).
Including all these "real" names automatically may be complicated, and doing it manually would probably be too much of an effort. A standard explanation of how to find these names using the Python console could be an alternative.
For instance:

> To get the names of the algorithm parameters for use in Python scripts and plugins, see "19.7 Using processing algorithms from the console".

## Checklist

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [x] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment]
See #2770?

**Comment by havatv** [comment]
Sorry, I had not noticed that one. #2770 should solve this! How far is it from being merged?

**Comment by DelazJ** [comment]
>How far is it from being merged?

really far... The prototype is not yet fixed and then the phase of replication (unless there's some automated process)

**Comment by havatv** [comment]
Is it worth doing a temporary fix similar to the one proposed here?
