### ISSUE TITLE
Wrong text in 3.4 version about 2.18 and 2.14

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS-Documentation#4325]
## Description

Page URL: https://docs.qgis.org/3.4/en/docs/user_manual/working_with_ogc/ogc_server_support.html

In the  link above, we can read:
```
Docs for ‘QGIS 2.18’. Visit http://docs.qgis.org/2.14 for QGIS 2.14 docs and translations.
```

**Comment by DelazJ** [comment]
That file does not exist and is full of incoherencies (mentions QGIS Testing, url contains 3.4 but shows on the left 2.18 docs and pressing the fix me link at the bottom opens a 404.
I remember we already had a report like this (see part of #2389 and a suggestion for a fix that is out of my scope)

**Comment by havatv** [comment]
Seems to have been fixed now (the link https://docs.qgis.org/2.14 works).

**Comment by DelazJ** [comment]
This I not the issue. The problem is that we keep some old files in a cache and they are still accessible while they shouldn't. I think it's a server side issue

**Comment by Gustry** [comment]
I confirm that the issue is still valid. I got a link using 2.14 in the URL on my search engine.
I switched to 3.4 by changing in the URL I still have this warning:
https://docs.qgis.org/3.4/en/docs/user_manual/working_with_vector/virtual_layers.html

It's indeed an old page, the new one is:
https://docs.qgis.org/testing/en/docs/user_manual/managing_data_source/create_layers.html#creating-virtual-layers

**Comment by DelazJ** [comment]
> I confirm that the issue is still valid. I got a link using 2.14 in the URL on my search engine.

I think the issue is there. You shouldn't get results from old releases (at least not among the first results). The rtd-theme I was testing for 3.10 docs (mentioned yesterday in psc-list) has a [canonical_url option](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-canonical_url) that, from my understanding, would fix this issue if we point it to a moving target like https://docs.qgis.org/latest And in the future, we can expect old releases get forgotten by search tools.
Otherwise @rduivenvoorde had you had time [as mentioned here](https://github.com/qgis/QGIS-Documentation/issues/2389#issuecomment-369886417) (In case it'd fix this issue) to 
> [..]clean up current testing web folder. The process of building on one server and then rsyncing to the actual webserver does indeed not cleanup old stuff.

I don't think that the option to redirect pages is maintainable in the long run.

**Comment by rduivenvoorde** [comment]
I cleaned up current master branch, so at least that one should be clean now.

Cleaning up 3.4 serving dir would be a little more difficult (as it is easy to remove everything... but will take some time to create all new languages). Can just do it though...
